pull_request_rules:
  - name: backport patches to 2021 branch
    conditions:
      - base=master
      - label=backport-2021
    actions:
      backport:
        branches:
          - rls/2021-gold-mnt
  - name: backport patches to 2020 branch
    conditions:
      - base=master
      - label=backport-2020
    actions:
      backport:
        branches:
          - rls/daal-2020-mnt
  - name: delete head branch after merge
    conditions:
      - head~=^renovate/
      - merged
    actions:
      delete_head_branch: {}
  - name: Review assigment for renovate requests
    conditions:
      - author=renovate[bot]
      - -closed
    actions:
      request_reviews:
        users:
          - napetrov
